### PR TITLE
Usernamenumber/rachel portal

### PR DESCRIPTION
**Pull request by usernamenumber**
This PR is a massive overhaul of the portal page. Here is a brief overview of the changes made:

* Integrates our WAP/captive portal functionality with the [RACHEL Project portal's](https://github.com/needlestack/rachel-content) support for simple content modules.
* Integrates @Ar2000jp's datasync roles from #42. These worked excellently, Ahmad! However, I did make a couple of changes. In particular, see 430223e5c904cfbe2126cc7a9f53e96fc903d595
* By default, portal starts a background rsync of all [RACHEL modules](http://dev.worldpossible.org/mods/) except for kalite and wikipedia, which are much bigger and get their own roles instead.
* Replaces the old, Apache-based Wikipedia role has been replaced with one that syncs the corresponding RACHEL module.
* Configures the kalite role to download a custom portal module for its self
  * RACHEL also has a [kalite module](http://geekdome.net/x2go/modules/kaos-en/), which might be worth looking at for ease of deployment (also, searchable from the portal page). However, their version removes all Django integration and all interactive components such as quizzes. Since our role keeps these things, and the cubie seems to have enough power to serve them, I just created our own RACHEL-compatible module to point to it. 
* Replaces the old bootstrap theme with something simpler
  * Apologies to Omar for this; it's mostly because I needed to make changes and don't know bootstrap very well. Feel free to re-incorporate it if you want! :)

One outstanding TODO (which IMO shouldn't keep this PR from being merged) is setting up an rsync repo for the kalite videos. It might be possible to use the videos that are already in the kaos-en RACHEL module for this.

### CODE REVIEW

**Comment by Ar2000jp** [comment]
The datasync_now handler is not being honored for some reason. Changing its name in the handler or the notify statement doesn't even throw an error. Ansible bug?

**Comment by Ar2000jp** [comment]
I'm still testing. Got stuck tracking down a bug. I should have mentioned that.
The datasync_now handler is not being called. I changed the handler itself to give me an indication that it was called, but got nothing. Probably an Ansible bug.

**Comment by Ar2000jp** [comment]
The sync scripts do "date >> {{ item.local_dir }}/sync_in_progress", but the local_dir is the same for most modules. The portal page sync notification is broken because of this.

**Comment by usernamenumber** [comment]
Argh! You're totally right. I "simplified" the configuration because I got lazy and realized I could just sync each module dir (minus the trailing "/") into the {{ module_dir }} instead of {{ module_dir }}/name. If I just go back and fix that, notification should work again. Good catch!

**Comment by usernamenumber** [comment]
Ok, I've committed a change that should fix this, but haven't had time to test. Please tell me if it works now.

**Comment by usernamenumber** [comment]
Hmm.. I also notice that I didn't add the wikipedia/meta directory in the initial commit, so it doesn't pull down the relevant module when enabled. Should be fixed now.

**Comment by Ar2000jp** [comment]
1- How about we rename the wikipedia role to wfs? We might want to add the real wikipedia one day.
2- The last commit uses the wrong rsync syntax.

**Comment by usernamenumber** [comment]
1- I'd be ok with that.
2- Which commit? I tested by removing a module dir and the sync scripts, and then re-running the playbook, and it sync'd fine.

**Comment by Ar2000jp** [comment]
Thw wfs meta file. It uses rsync without / at the end.

**Comment by Ar2000jp** [comment]
1- The datasync_now handler is still not working. Maybe we should convert it to a task and just run it per script?
2- Maybe we should change {$mod['dir']} to  {$mod['file']} in the sync in progress message. This gives "powertyping" instead of "modules/powertyping", which I think is a bit more intuitive.
3- Should I test the sphider search engine?

Great work so far!

**Comment by usernamenumber** [comment]
I just committed a fix for the wikipedia rsync command and renamed the wikipedia module to wikipedia_for_schools (wfs is less annoying to type, but wikipedia_for_schools makes it more obvious what the role is for and matches the name of the corresponding rachel role. 

I'm having a weird problem with the bind module, which is making testing difficult. These changes are simple enough that since this branch isn't actually being used by anyone yet, I'm committing now and will fix if there's a problem. If you get a chance to test, let me know if you have any problems!

**Comment by usernamenumber** [comment]
...and speaking of problems, in response to your other comment:

1- Hmm, it seemed to work for me. Are you seeing an error? If so, what does it say?

2- Sure. I noticed that `modules/typing` looks a bit weird too, but fixing it wasn't a priority for me. Go ahead and submit a patch for it to this branch.

3- I would *love* it if you could figure Sphider out. I started digging through the docs and concluded "this looks like a really cool thing that I can't justify spending the time it would take to learn right now". I think figuring out how to use it for the rachel modules, and how to plug it into other things like edX courses, would be a great help!

**Comment by usernamenumber** [comment]
Tested the wikipedia_for_schools role and it seems to work fine. If the problem you're seeing is that new modules aren't appearing in the portal right away, it's because that doesn't happen until an `index.htmlf` file is found, and those seem to rsync last. If you look in `/var/log/syslog`, do you see log messages about syncs starting and ending?

**Comment by usernamenumber** [comment]
I'd like to get this merged into master asap, and sphider can be worked on in a separate branch. Can you confirm that modules are syncing for you, even if they don't appear on the portal until close to the end of the initial sync? If that's the case, I'll go ahead and merge, and we can submit incremental improvements from there.

**Comment by Ar2000jp** [comment]
Everything seems to work fine. The only thing not working is the datasync_now handler. It just skips over it. This is the message: "NOTIFIED: [cron_datasync | datasync_now] skipping: [127.0.0.1]". Nothing in syslog from the sync scripts.

The modules are syncing no problem, sync-in-progress working, sync scripts are correct, the portal seems to be OK. Anything else I should test?

I test using fresh Ubuntu 14.04 VMs. Using a custom localconfig.yml file, and the bootstrap.sh script.

PS: Sorry for delaying the branch. But I thought it's better to merge tested working code.

**Comment by usernamenumber** [comment]
Oh yes, I didn't mean to sound like I was criticizing you for slowing
anything down (you're the only one helping to test right now, and I
appreciate it!), just saying I'd like to do the remaining noncritical tasks
in their own branches so *they* don't slow down release.

Thanks for your help!

--Brad

**Comment by Ar2000jp** [comment]
I'm sorry if it sounded negative, too. I'm just new to working in a team.

If there's nothing else you want me to test, then please go ahead and merge
it. Everything seems OK to me. The datasync_now handler is not critical,
and can be fixed later.

**Comment by usernamenumber** [comment]
It looks like the datasync_now issue is due to a bug in Ansible. :( https://github.com/ansible/ansible/issues/8684

**Comment by Ar2000jp** [comment]
The sync_now task is working without problems.

**Comment by usernamenumber** [comment]
Great! I'm delaying pushing this branch to master because several of the Rachel modules have built-in search boxes that assume the presence of rsphider. Rather than push out "support" for a bunch of broken modules, I think it's worth spending some more effort on getting it working. I'm about to commit some work I've been doing on this into the branch, just in case you've also been working on it.

Basically, I've added a role that installs rsphider and sets up its database, but manual configuration is still required to make it index the available modules. I'd love to figure out a way to automate that. It will probably require figuring out what gets added to the rsphider database when you tell it to index a site and then creating ansible tasks that put that into the db when you install the corresponding module.

**Comment by usernamenumber** [comment]
I've started taking notes on how to do the things that will need to be automated here: https://github.com/tunapanda/provision/wiki/rsphider-automation-notes

**Pull request merged**
