### PR TITLE
Vidtest stress tester with anti-caching filenames

### PR DESCRIPTION
**Pull request by usernamenumber**
This creates a role that sets up a `/vidtest` location on the main web server. At this location a short video is played on a loop. Each time the page is loaded, a random number is incorporated into the filename (stripped out by nginx when the request is processed) so that browsers should (though I haven't looked at the network traffic to confirm it) always get it from the server, never a local cache since the filenames never (well, rarely) match between page loads.

This can be used to load-test the server's video streaming capabilities.

### CODE REVIEW

**Comment by usernamenumber** [comment]
@devalih: Any chance you could confirm that this works for you (just add `vidtest__enabled: true` to your localconfig.yml) and then see how many people you can get viewing the page at once? (assuming you have a cubietruck by now)

**Comment by Ar2000jp** [comment]
Tested in an Ubuntu 14.04 VM (same as cubie). Working as expected. Checked with Firebug.
The cubie is at my place, and it's busy with the port, so we can't test this right now.

**Comment by usernamenumber** [comment]
I've tested it on my cubie. Had five clients playing the video at once with
no playback problems. If it looks OK to you, I'll go ahead and merge this
branch when I wake up for our meeting. :)

**Comment by Ar2000jp** [comment]
Everything looks OK to me. Please go ahead and merge it.

**Pull request merged**
